from app.schemas.core import (
    BadcaseSummary,
    DatasetVersion,
    DashboardSummary,
    DatasetSummary,
    PerceptionSummary,
    RLSummary,
    Scenario,
    V3BacklogItem,
)


SCENARIOS = [
    Scenario(
        id="scenario-dry-flat-clear",
        name="干燥短草、平地、清晰边界",
        grass_type="bermuda",
        grass_height="short",
        moisture="dry",
        terrain="flat",
        boundary_type="clear",
        obstacle_types=["tree"],
        lighting="normal",
        weather="sunny",
        season_time="summer-morning",
        coverage_count=410,
        risk_level="low",
        sensor_modalities=["camera", "lidar", "ultrasonic"],
        dynamic_obstacle_pattern="none",
    ),
    Scenario(
        id="scenario-wet-slope-shadow",
        name="湿高草、坡地、阴影",
        grass_type="mixed",
        grass_height="tall",
        moisture="wet",
        terrain="slope",
        boundary_type="soft-shadow",
        obstacle_types=["stone", "fence"],
        lighting="shadow",
        weather="after-rain",
        season_time="spring-evening",
        coverage_count=68,
        risk_level="medium",
        sensor_modalities=["camera", "imu", "gnss"],
        dynamic_obstacle_pattern="none",
    ),
    Scenario(
        id="scenario-dense-dynamic-pet",
        name="密集障碍物、动态宠物、不规则边界",
        grass_type="mixed",
        grass_height="medium",
        moisture="mixed",
        terrain="irregular-slope",
        boundary_type="irregular",
        obstacle_types=["person", "pet", "stone", "tree", "fence"],
        lighting="glare-and-shadow",
        weather="sunny",
        season_time="autumn-afternoon",
        coverage_count=22,
        risk_level="high",
        sensor_modalities=["camera", "lidar", "ultrasonic", "trajectory"],
        dynamic_obstacle_pattern="person-pet-crossing",
    ),
]


DATASETS = [
    DatasetVersion(
        id="dataset-v1",
        name="baseline mower perception dataset",
        sample_count=2400,
        source="现场外采 + 合成增强",
        scenario_distribution={
            "scenario-dry-flat-clear": 410,
            "scenario-wet-slope-shadow": 42,
            "scenario-dense-dynamic-pet": 8,
        },
        annotation_schema_version="label-schema-v1",
        qc_status="baseline QC completed",
        quality_score=0.78,
        sensor_modalities=["camera"],
        immutable_after_training=True,
        linked_training_runs=["det-yolo-v1"],
        linked_evaluation_reports=["eval-perception-v1"],
        linked_badcases=["badcase-small-stone-001"],
        known_limitations=["强光样本不足", "动态障碍样本不足", "无模拟 LiDAR"],
    ),
    DatasetVersion(
        id="dataset-v2",
        name="v2 sensor-aware closed-loop dataset",
        sample_count=3180,
        source="现场外采 + 机端回传 + 仿真生成",
        scenario_distribution={
            "scenario-dry-flat-clear": 410,
            "scenario-wet-slope-shadow": 68,
            "scenario-dense-dynamic-pet": 22,
        },
        annotation_schema_version="label-schema-v2",
        qc_status="QC 通过，12 条待复核",
        quality_score=0.86,
        sensor_modalities=["camera", "lidar", "ultrasonic", "imu", "gnss", "trajectory"],
        immutable_after_training=True,
        linked_training_runs=["det-yolo-v2", "seg-boundary-v1"],
        linked_evaluation_reports=["eval-unseen-014", "eval-perception-v2"],
        linked_badcases=["badcase-shadow-boundary-001", "badcase-ppo-stuck-014"],
        known_limitations=["雨天样本仍偏少", "密集动态障碍覆盖不足", "真实 rosbag/MCAP 日志待 V3 接入"],
        v3_real_log_sources=["rosbag", "MCAP", "fleet-upload"],
    ),
]


V3_BACKLOG = [
    V3BacklogItem(
        id="V3-001",
        priority="P0",
        title="ROS 2 / Gazebo 或 Isaac Sim 接入",
        module="仿真系统",
        expected_value="接近真实机器人开发流程",
        dependency="SimulatorAdapter",
        version_target="V3",
        status="planned",
    ),
    V3BacklogItem(
        id="V3-002",
        priority="P0",
        title="真实 LiDAR / RTK / GNSS / IMU 日志接入",
        module="数据管线",
        expected_value="覆盖真实多传感器数据要求",
        dependency="SensorFrame",
        version_target="V3",
        status="planned",
    ),
    V3BacklogItem(
        id="V3-003",
        priority="P1",
        title="多传感器融合 baseline",
        module="感知融合",
        expected_value="从视觉扩展到多源感知",
        dependency="real sensor logs",
        version_target="V3",
        status="planned",
    ),
    V3BacklogItem(
        id="V3-004",
        priority="P1",
        title="TensorRT / 量化边缘部署",
        module="部署评估",
        expected_value="评估延迟、功耗和内存约束",
        dependency="ONNX export records",
        version_target="V3",
        status="planned",
    ),
]


def build_dashboard_summary() -> DashboardSummary:
    return DashboardSummary(
        product_name="LawnBot AI 训练工作台",
        target_version="V2",
        architecture_mode="V3-ready",
        ui_language="zh-CN",
        dataset=DatasetSummary(
            version_id="dataset-v2",
            coverage_rate=0.72,
            sample_count=3180,
            weak_scenarios=["雨天", "强眩光", "窄边界", "密集动态障碍"],
            qc_status="QC 通过，12 条待复核",
        ),
        perception=PerceptionSummary(
            model_id="det-yolo-v2",
            task="obstacle-detection",
            mAP=0.81,
            recall=0.78,
            onnx_status="ready",
            latency_ms=38,
        ),
        rl=RLSummary(
            policy_id="ppo-v2",
            algorithm="PPO",
            unseen_success_rate=0.68,
            coverage_rate=0.82,
            dynamic_obstacle_response_ms=900,
            curriculum_stage="curriculum-stage-3",
        ),
        badcases=BadcaseSummary(
            open_count=37,
            high_severity_count=11,
            recommendation_count=24,
            top_root_causes=[
                "reward 对局部循环惩罚不足",
                "动态障碍样本不足",
                "阴影边界标注不稳定",
            ],
        ),
        v3_backlog=V3_BACKLOG,
        workflow=["场景", "Dataset/QC", "感知训练", "RL 仿真", "泛化评估", "Badcase 决策"],
        source_versions={
            "dataset": "dataset-v2",
            "model": "det-yolo-v2",
            "policy": "ppo-v2",
            "evaluation": "eval-unseen-014",
        },
    )
